# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/ps_development.sqlite3

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/ps_test.sqlite3